### PR TITLE
Post: Accelerate your React testing with Enzyme

### PR DESCRIPTION
**Pull request by alextaylor000**
Please review! :eyes: 

screencapture-localhost-4000-2016-03-10-accelerate-your-react-testing-with-enzyme-html-1457729345750

### CODE REVIEW

**Comment by patdryburgh** [comment]
Should “frontends” be “front-ends”?

**Comment by patdryburgh** [comment]
Is that a hyphen or an em dash after the word “test”? Em dashes can be written as `&mdash;`

**Comment by alextaylor000** [comment]
@patdryburgh I'll change that to an em-dash. I looked up "frontend," it seems to be [acceptable multiple ways](http://english.stackexchange.com/a/34953). But the jury's still out!

**Comment by patdryburgh** [comment]
@alextaylor000 Cool :) The “shallow, full and static” might need an oxford comma.

**Comment by patdryburgh** [comment]
“through a jungle of nested arrays to in order” doesn't need “to”

**Comment by patdryburgh** [comment]
Lastly: “anything you want” likely doesn't need a double emphasis (bold and italic). One or the other will likely suffice ;)

**Comment by alextaylor000** [comment]
@patdryburgh super weird, I actually just used one underscore for italicizing, but Jekyll is taking it and making it bold AND italic! I'll see if there's a way around it.

**Comment by alextaylor000** [comment]
@patdryburgh OK it looks like that emphasis is actually coming from the font or styling, Jekyll is rendering it correctly with just `<em>anything you want</em>`. Bizzare.

**Comment by patdryburgh** [comment]
@alextaylor000 Well then, that must be my bad on the CSS side. Leave it as-is and we'll fix it whenever we get to fix up some style bugs.

**Comment by pcreux** [comment]
This article is great! It highlights the benefits of enzyme and gives an idea of how to use it without going too much into the details. Love it!

(That being said, I didn't take time to try to find typos and such)

**Comment by alextaylor000** [comment]
Thanks @pcreux! I'll hit "publish" on Tuesday after Paulo's article goes up.

**Pull request merged**
